### ISSUE TITLE
Text attributes and colors

### ISSUE THREAD

**Issue by BrianHoldsworth** [JulienPalard/vt100-emulator#4]
HI. This may not be an issue, but just a misunderstanding. The headless terminal does not seem to process text attributes and colors. Is this just a limitation of the control codes currently handled, and so it could be easily extended?

**Comment by JulienPalard** [comment]
Hi.

Thanks for reporting. You're right, the headless terminal does not process text attributes and color. In fact they are two separated things, both can easily be implemented.

First, text attributes like bold, underscore, blink, and negative (reverse) [are from the VT100](http://vt100.net/docs/vt100-ug/chapter3.html#SGR), but unimplemented in my code (see later).

Next, the text colors are not from the VT100, but can still be implemented (maybe in another file, still using the lw_terminal_parser as a backend parser, if we find in which terminal was the color introduced?).

 - lw_terminal_parser already handle it so it does not need modifications
 - lw_terminal_vt100.c already registers a callback for text attr and colors, [this->lw_terminal->callbacks.csi.m = SGR;]( https://github.com/JulienPalard/vt100-emulator/blob/master/src/lw_terminal_vt100.c#L971)
 - however, lw_terminal_vt100.c does nothing with it: [    /* Just ignore them for now, we are rendering pure text only */
](https://github.com/JulienPalard/vt100-emulator/blob/master/src/lw_terminal_vt100.c#L445)

You'll have to add a new attribute at the end of the [`struct lw_terminal_vt100`](https://github.com/JulienPalard/vt100-emulator/blob/master/src/lw_terminal_vt100.h#L90) to store attributes and colors.

And finally probably expose a way to ask for those attributes around [lw_terminal_vt100_getlines](https://github.com/JulienPalard/vt100-emulator/blob/master/src/lw_terminal_vt100.c#L911).

**Comment by BrianHoldsworth** [comment]
Hi. Thanks for the explanation. I suppose in the case of colors, its not VT100 emulation that we are talking about. The CSI 30 through 49 codes used for colors come from ANSI terminal emulation, and are common in modern terminal emulators, but were never an aspect of the VT100's functionality.

Emulating character attributes along with the text would allow the terminal to reconstitute the "look" of the hosted application, but maybe that is not important for your use-case. For my case, I think I would want to reconstitute the "look" as well as the text.

I'd be inclined to use only a single byte attribute per character byte, to keep the code and data structures simple and "symmetrical". So, it could either be FG color + BG color, or it could be FG color + bits for the text style, but couldn't be all 3 of those. Does something like that break compatibility for your onw use-cases? It seems one could just fetch text lines and ignore attributes, If they so desired, right?

**Comment by JulienPalard** [comment]
To avoid breaking compatibility, just store those metadata in another attribute of the structure, and don't modify actual public getters, just add others.

I'd probably prefer something like:
 - A byte array of the same shape of screen to store the text style
 - A byte array of the same shape of screen to store the text color
 - A new function like lw_terminal_vt100_getlines to retrieve the styles
 - A new function like lw_terminal_vt100_getlines to retrieve the colors
 - Maybe a new function like vt100_headless_getlines, but giving a "high level" merged representation (char + color + style) of each characters for each lines, allowing to expose it easily in Python, if you need it.

This way you're not breaking any existing API, and you get fg, bg, and color. I'm OK if you implement this in lw_terminal_vt100 instead of creating a lw_terminal_ansi.

**Comment by JulienPalard** [comment]
Looks like someone did it last year: https://github.com/gulrotkake/vt100-emulator/commit/6406a8e80f8672e2fd122c28036069adbac81d7e

**Comment by BrianHoldsworth** [comment]
I see that. I made similar changes to the SGR callback, but then also made a bunch of other changes to allow converting back into ANSI codes too.
https://github.com/BrianHoldsworth/vt100-emulator/tree/ansi

**Comment by JulienPalard** [comment]
Ok, so, I'm closing the issue.
